# Generated by Django 3.0.8 on 2020-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(db_column='Number', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_column='Name', max_length=96, null=True),
        ),
    ]
