# Generated by Django 3.0.8 on 2020-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200718_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, db_column='Type', max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_column='Name', max_length=96, null=True, unique=True),
        ),
    ]
